-- 11-ddl-compatibility.sql: Redshift type domain aliases and DDL compatibility notes
--
-- Type Domains
-- These domains allow Redshift DDL that uses proprietary type names to be
-- loaded without modification after DDL preprocessing.

-- SUPER: Redshift's semi-structured data type. Maps to JSONB in PostgreSQL.
DO $$ BEGIN
  CREATE DOMAIN super AS jsonb;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- VARBYTE: Redshift's variable-length binary type. Maps to BYTEA in PostgreSQL.
DO $$ BEGIN
  CREATE DOMAIN varbyte AS bytea;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- HLLSKETCH: Redshift's HyperLogLog sketch type. Maps to BYTEA in PostgreSQL.
DO $$ BEGIN
  CREATE DOMAIN hllsketch AS bytea;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- DDL Compatibility Notes
-- ---------------------------------------------------------------------------
--
-- IDENTITY columns:
--   Redshift: col INTEGER IDENTITY(seed, step)
--   PostgreSQL equivalent: col INTEGER GENERATED BY DEFAULT AS IDENTITY
--   The ddl-preprocessor.sh script performs this conversion automatically.
--   Note: Redshift IDENTITY does not enforce uniqueness; PostgreSQL does.
--   If tests insert explicit values into identity columns, use
--   GENERATED BY DEFAULT (not GENERATED ALWAYS) to allow overrides.
--
-- Redshift-only DDL clauses stripped by ddl-preprocessor.sh:
--   ENCODE <algorithm>       -- column compression encoding (ignored in PG)
--   DISTSTYLE KEY|ALL|EVEN|AUTO -- distribution style (ignored in PG)
--   DISTKEY (column)         -- distribution key column (ignored in PG)
--   SORTKEY (col1, ...)      -- sort key columns (ignored in PG)
--   COMPOUND SORTKEY (...)   -- compound sort key (ignored in PG)
--   INTERLEAVED SORTKEY (...) -- interleaved sort key (ignored in PG)
--   AUTO REFRESH YES|NO      -- materialized view auto refresh (ignored in PG)
--   BACKUP YES|NO            -- snapshot backup setting (ignored in PG)
--
-- Constraint behavior gap:
--   Redshift declares but does NOT enforce PK/UNIQUE/FK constraints.
--   PostgreSQL DOES enforce them. Tests that insert duplicate rows will
--   fail locally but succeed on real Redshift.
