#!/usr/bin/env bash
# =============================================================================
# ddl-preprocessor.sh
# Strips Redshift-specific DDL clauses that are not supported by PostgreSQL
# and converts Redshift IDENTITY syntax to PostgreSQL standard syntax.
#
# Usage:
#   ddl-preprocessor.sh <input_file> <output_file>
#
# Examples:
#   ddl-preprocessor.sh schema_redshift.sql schema_postgres.sql
#   ddl-preprocessor.sh - -   # read stdin, write stdout
# =============================================================================

set -euo pipefail

INPUT="${1:--}"
OUTPUT="${2:--}"

usage() {
  echo "Usage: $(basename "$0") <input_file> <output_file>"
  echo "  Use - for stdin/stdout."
  exit 1
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
fi

# ---------------------------------------------------------------------------
# Build sed script
# ---------------------------------------------------------------------------
# All patterns are applied in-order with GNU/BSD compatible sed (-E for ERE).
# We use a multi-expression script so the file is read only once.
#
# Rules:
#   1.  ENCODE <algorithm>           — Redshift column-level encoding hint
#   2.  DISTSTYLE { EVEN|KEY|ALL|AUTO }
#   3.  DISTKEY ( col )
#   4.  [COMPOUND|INTERLEAVED] SORTKEY ( col [, col] )
#   5.  AUTO REFRESH { YES | NO }   — materialized view option
#   6.  BACKUP { YES | NO }         — table option
#   7.  IDENTITY(seed, step)        — converted to PostgreSQL standard syntax
#       GENERATED BY DEFAULT AS IDENTITY
# ---------------------------------------------------------------------------

SED_SCRIPT='
# ---- ENCODE clause (must come before ENCODE keyword in DISTSTYLE etc.) ----
# Matches: ENCODE <word>  at word boundary, case-insensitive
s/[[:space:]]*ENCODE[[:space:]]+[A-Za-z0-9_]+//gI

# ---- DISTSTYLE ----
# Matches: DISTSTYLE { EVEN | KEY | ALL | AUTO }
s/[[:space:]]*DISTSTYLE[[:space:]]+(EVEN|KEY|ALL|AUTO)//gI

# ---- DISTKEY ( ... ) ----
# Matches: DISTKEY ( column_name )
s/[[:space:]]*DISTKEY[[:space:]]*\([^)]*\)//gI

# ---- [COMPOUND|INTERLEAVED] SORTKEY ( ... ) ----
# The optional prefix + SORTKEY ( ... ) — must handle multi-line
# Single-line version (most common):
s/[[:space:]]*(COMPOUND[[:space:]]+|INTERLEAVED[[:space:]]+)?SORTKEY[[:space:]]*\([^)]*\)//gI

# ---- AUTO REFRESH YES|NO ----
s/[[:space:]]*AUTO[[:space:]]+REFRESH[[:space:]]+(YES|NO)//gI

# ---- BACKUP YES|NO ----
s/[[:space:]]*BACKUP[[:space:]]+(YES|NO)//gI

# ---- IDENTITY(seed, step) → GENERATED BY DEFAULT AS IDENTITY ----
# Redshift: col INTEGER IDENTITY(1, 1)
# PostgreSQL: col INTEGER GENERATED BY DEFAULT AS IDENTITY
s/[[:space:]]*IDENTITY[[:space:]]*\([[:space:]]*[0-9]+[[:space:]]*,[[:space:]]*[0-9]+[[:space:]]*\)/ GENERATED BY DEFAULT AS IDENTITY/gI
'

# ---------------------------------------------------------------------------
# Execute
# ---------------------------------------------------------------------------
if [[ "$INPUT" == "-" && "$OUTPUT" == "-" ]]; then
  sed -E "$SED_SCRIPT"
elif [[ "$INPUT" == "-" ]]; then
  sed -E "$SED_SCRIPT" > "$OUTPUT"
elif [[ "$OUTPUT" == "-" ]]; then
  sed -E "$SED_SCRIPT" "$INPUT"
else
  sed -E "$SED_SCRIPT" "$INPUT" > "$OUTPUT"
fi
